# Site settings
title:          Zheng Shen
water:			Water
description:    "Minimal Jekyll theme for storytellers"
url:            "https://ZayneS.github.io"

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings markdown engine
markdown:       redcarpet

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Collections
collections:
  designs: 
    output: true 
    permalink: /my-designs/:name

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
